- DailyCode/prime-check.py
- Sorting_Searching/selection_sort.py
Have added selection sort in the sorting folder.
> Added Selection Sort

- Interview_questions/maximum_subarray_problem.py
> added maximum_subarray_problem.py

- Sorting_Searching/Better_Mergesort.py
The previous merge sort is merely for one example but I've made it in a way that anyone can run it for any number of test cases.
I change the mergesort file to be more usable,i.e' can be used by any test case.
I'm actively waiting to comment, so please have a convo before deleting.
> Better Merge Sort

- Sorting_Searching/countSort.py
I have made changes in Sorting_Searching folder added countSort.py file including stable and unstable count sort.
> Added Counting Sort

- Strings/boyer_moore_search.py
- Strings/manacher.py
I have made changes in String folder added manacher and  boyer moore search algorithms.
> Added Boyer Moore search and manacher algorithms

- Strings/strings_consec.py
Added a function to remove consecutive characters from strings stored in the 'add.txt' file.
> Add function to remove consecutive characters from strings

- Interview_questions/rain_water_saving.py
> added Rain Water Saving Interview Problem (FAANG)

- DailyCode/calculator.py
Hey, The calaculator is done :pray:
> calculator.py added at DailyCode

- Dynamic_Programming/Fibonacci.py
if there are any better optimization, feel free to PR.
> add fibonacci with memoization in dynamic programming

- Patterns/rhombo_pattern.py
- Sorting_Searching/matrix_search.py
* * * * * * * * * 
* * * *   * * * * 
* * *       * * * 
* *           * * 
*               * 
* *           * * 
* * *       * * * 
* * * *   * * * * 
* * * * * * * * * 
rhombo patter finished :rhinoceros:
> Rhombus pattern

- Sorting_Searching/matrix_search.py
Matrix search completed :jack_o_lantern:
> Matrix search

- Array/Rotate_Left.py
> Added the program: Rotate an array to the left by 3 positions

- Sorting_Searching/count_sort_stable.py
Added the program of Stabled Counting Sort in the repo.
> Added Stabled count sort

- Sorting_Searching/Shell_Sort.py
> Added Shell Sort

- Array/sort_an_arr_of_0s_1s_2s.py
- Interview_questions/peak_element.py
- Interview_questions/single_element_in_sorted_arr_.py
- Maths/Fibonacci.py
Added two Question Solutions in the Interview folder... (as a part of Hacktober fest :p )
> Interview qs

- Data_Structures/avl_tree.py
> Added avl_tree.py under data structures folder

- Maths/Maximum height triangle.py
Given integers  a and b, find the smallest integer h, such that there exists a triangle of height h, base b, having an area of at least a .
> hackerrank-problem

- Maths/palindrome_number_checker.py
It checks whether the number is palindrome number  or not
> Added new python file that checks palindrome number

- Array/Rotate_Left.py
- Array/Rotate_Right.py
A better program with less complexity, the previous program takes more time and storage space
> Rotating Array

- Maths/decimal_to_octal.py
> Decimal to octal

- Maths/Geometry_Calculator.py
Added Maths => Geometry_Calculator.py
Formulas are included for 4 Geometry Figures (Cube,Cuboid,Ball,Pyramid)
Pull Request to Issue #76 
Written in Python
> Add Geometry_Calculator.py with 4 Geometry Figures

- Interview_questions/FizzBuzz.py
> Add FizzBuzz

- Sorting_Searching/bubblesort.py
Hacktoberfest contribution: Adding bubblesort algo in Python
> feat: add bubblesort algorithm

- Strings/letter_case_permutation.py
- Strings/recursive_palindrome.py
- Strings/vowel_count.py
- vowel_count code added
- letter_case_permutation code added
- recursive_palindrome code added
> feature: some more algorithms for Strings folder added

- Sorting_Searching/matrix_in_search.py
#89 Issue solved.
Added the python code file for "sorted matrix search" for issue #89, please check this, and if everything is fine then please merge the pull request.
> Matrix search code added for a sorted matrix
